language: node_js
node_js:
  - 17

services:
  - docker

script:
  # - echo "logging into dockerhub..."
  # - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - echo "logging into heroku registry"
  - docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
  - echo "building image..."
  - docker build -t "just-tech-news:latest" -f Dockerfile.backend .
  - echo "tagging docker image..."
  - docker tag "just-tech-news:latest" "registry.heroku.com/just-tech-news:latest/backend"
  - echo "pushing to dockerhub registry..."
  - docker push "registry.heroku.com/just-tech-news:latest/backend"


# deploy:
#   provider: heroku
#   api_key:
#     secure: "YOUR ENCRYPTED API KEY"