language: node_js
node_js:
  - 17

services:
  - docker

before_install:
- wget -qO- https://toolbelt.heroku.com/install.sh | sh #installed heroku CLI
- echo "logging into heroku registry"
- docker login -u "$HEROKU_USERNAME" --password=$(heroku auth:token) registry.heroku.com #logged in

script:
  # - echo "logging into dockerhub..."
  # - docker login -u $DOCKER_USER -p $DOCKER_PASS
  # - echo "logging into heroku registry"
  # - docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
  # - echo "building image..."
  # - docker build -t "just-tech-news-dbcurtis" -f Dockerfile .
  # - echo "tagging docker image..."
  # - docker tag "just-tech-news-dbcurtis" "registry.heroku.com/just-tech-news-dbcurtis/web"
  # - echo "pushing to dockerhub registry..."
  # - docker push "registry.heroku.com/just-tech-news-dbcurtis/web"
  - heroku container:push web --app just-tech-news-dbcurtis

deploy:
  provider: script
  script:
    heroku container:release web --app just-tech-news-dbcurtis
# deploy:
#   provider: heroku
#   api_key:
#     secure: $HEROKU_API_KEY
#   app: just-tech-news-dbcurtis
    