language: node_js
node_js:
  - 17

services:
  - docker

before_script:
  - npm install
  - echo "run unit tests"
  - npm run test

script:
  - echo "logging into heroku registry"
  - docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
  - echo "building image..."
  - docker build -t "just-tech-news-dcurtis" -f Dockerfile .
  - echo "tagging docker image..."
  - docker tag "just-tech-news-dcurtis" "registry.heroku.com/just-tech-news-dcurtis/web"
  - echo "pushing to dockerhub registry..."
  - docker push "registry.heroku.com/just-tech-news-dcurtis/web"

deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app: just-tech-news-dcurtis
  
    