apiVersion: apps/v1
kind: Deployment
metadata:
  name: just-tech-news
spec:
  selector:
    matchLabels:
      app: just-tech-news
  template:
    metadata:
      labels:
        app: just-tech-news
    spec:
      containers:
        - name: just-tech-news
          imagePullPolicy: Always
          image: "registry.digitalocean.com/pomoduck/just-tech-news:v1.0.0-prod"
          ports:
            - containerPort: 3001
          env:
            - name: DB_CONNECTION
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: DB_CONNECTION
---
apiVersion: v1
kind: Service
metadata:
  name: express-service
spec:
  selector:
    app: just-tech-news
  type: LoadBalancer
  ports:
    - port: 3001
      targetPort: 3001
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: express-configmap
data:
  EXPRESS_SERVICE: express-service.default.svc.cluster.local
